import type { Finding, Report } from '@i18n-xray/contracts'
import { CLIENT_SCRIPT } from './client-script'
import { embedJson, escapeHtml } from './html'
import { SEVERITY_LABEL, severityForRate } from './severity'
import type { Severity } from './severity'
import { STYLES } from './styles'

type DeadKey = Extract<Finding, { kind: 'dead-key' }>
type ValueDuplicate = Extract<Finding, { kind: 'value-duplicate' }>
type LocaleGap = Extract<Finding, { kind: 'locale-gap' }>
type Convention = Extract<Finding, { kind: 'convention' }>

type NamespaceView = {
  name: string
  keys: number
  dead: DeadKey[]
  duplicates: ValueDuplicate[]
  /** Distinct keys of this namespace caught in a cross-namespace duplicate. */
  duplicated: number
  issues: number
  severity: Severity
}

/**
 * Render a validated `report.json` into one self-contained HTML document.
 *
 * Everything is inlined — no stylesheet link, no script src, no font or image
 * request — because the artefact's job is to survive being downloaded from
 * Slack and opened offline from `file://`.
 */
export function renderReport(report: Report): string {
  const namespaces = rollUpNamespaces(report)
  const conventions = report.findings.filter(
    (finding): finding is Convention => finding.kind === 'convention',
  )
  const localeGaps = report.findings.filter(
    (finding): finding is LocaleGap => finding.kind === 'locale-gap',
  )

  // Open on the namespace that most needs attention, so a shared report leads
  // with its worst news rather than an empty panel.
  const worst = [...namespaces].sort(
    (a, b) => b.issues - a.issues || b.keys - a.keys || (a.name < b.name ? -1 : 1),
  )[0]

  const embedded = {
    initialSelection: worst?.name ?? null,
    namespaces: namespaces.map((ns) => ({
      name: ns.name,
      label: ns.name,
      keys: ns.keys,
      dead: ns.dead.length,
      duplicated: ns.duplicated,
      severity: ns.severity,
      severityLabel: SEVERITY_LABEL[ns.severity],
    })),
  }

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>i18n-xray report</title>
<script>document.documentElement.classList.add('has-js')</script>
<style>${STYLES}</style>
</head>
<body>
<div class="wrap">
${renderSilence(report)}
${renderHeader(report)}
${renderTreemap(report, namespaces)}
${namespaces.map((ns) => renderNamespaceDetail(ns, worst?.name)).join('\n')}
${renderGlobalFindings(conventions, localeGaps)}
<footer>
  Generated by i18n-xray. Coarse where it cannot be certain: fogged and unattributed keys are
  kept alive on purpose, so a live key is never reported dead.
</footer>
</div>
<div id="tooltip" role="presentation"></div>
<script id="report-data" type="application/json">${embedJson(embedded)}</script>
<script>${CLIENT_SCRIPT}</script>
</body>
</html>
`
}

/** Group findings under the namespace their KeyIds belong to. */
function rollUpNamespaces(report: Report): NamespaceView[] {
  const dead = new Map<string, DeadKey[]>()
  const duplicates = new Map<string, ValueDuplicate[]>()
  const duplicatedKeys = new Map<string, Set<string>>()

  for (const finding of report.findings) {
    if (finding.kind === 'dead-key') {
      push(dead, namespaceOf(finding.key), finding)
    } else if (finding.kind === 'value-duplicate') {
      for (const namespace of new Set(finding.keys.map(namespaceOf))) {
        push(duplicates, namespace, finding)
      }
      for (const key of finding.keys) {
        const seen = duplicatedKeys.get(namespaceOf(key)) ?? new Set<string>()
        seen.add(key)
        duplicatedKeys.set(namespaceOf(key), seen)
      }
    }
  }

  return report.summary.namespaces.map(({ name, keys }) => {
    const duplicated = duplicatedKeys.get(name)?.size ?? 0
    const deadHere = dead.get(name) ?? []
    const issues = deadHere.length + duplicated
    return {
      name,
      keys,
      dead: deadHere,
      duplicates: duplicates.get(name) ?? [],
      duplicated,
      issues,
      severity: severityForRate(keys === 0 ? 0 : issues / keys),
    }
  })
}

/** `"ns:a.b.c"` → `"ns"`. The KeyId format is fixed in CLAUDE.md. */
function namespaceOf(keyId: string): string {
  const at = keyId.indexOf(':')
  return at === -1 ? keyId : keyId.slice(0, at)
}

function push<T>(into: Map<string, T[]>, key: string, value: T): void {
  into.set(key, [...(into.get(key) ?? []), value])
}

/**
 * Constitution rule 3 travels with the artefact. A report whose scan found no
 * hook bindings must never look like a clean bill of health, including when
 * someone opens the HTML with no memory of how it was produced.
 */
function renderSilence(report: Report): string {
  if (!report.summary.silenceWarning) return ''
  return `<div class="silence card">
  <h2>Suspicious silence — these findings are unreliable</h2>
  <p>
    The scan found <code>t()</code> calls but <strong>zero</strong> hook bindings anywhere in
    ${report.summary.files.total} scanned files. The configured hook
    (<code>${escapeHtml(report.config.hooks.join(', '))}</code>) is probably not the one this
    codebase uses — many wrap <code>useTranslation</code> in their own. Re-run with
    <code>--hook &lt;yourWrapperHook&gt;</code> before trusting anything below.
  </p>
</div>`
}

function renderHeader(report: Report): string {
  const { totals, keys } = report.summary
  const blind = round(keys.fogPct + keys.unattributedPct)
  const buckets: Array<[Severity, string, number, string]> = [
    ['good', 'verified', keys.verified, 'a bound file names the key literally'],
    ['warning', 'fog-alive', keys.fogAlive, 'kept alive by a dynamic pattern'],
    ['serious', 'unattributed', keys.wideningAlive, 'kept alive by an unattributed file'],
    ['critical', 'dead', keys.dead, 'nothing references it'],
  ]

  return `<header class="card">
  <div class="masthead">
    <h1>i18n-xray report</h1>
    <p class="config">
      <code>${escapeHtml(report.config.srcDir)}</code> ·
      <code>${escapeHtml(report.config.localesDir)}</code> ·
      hook <code>${escapeHtml(report.config.hooks.join(' '))}</code> ·
      <code>${escapeHtml(report.config.localesPattern)}</code>
    </p>
  </div>

  <div class="stat-row">
    ${stat(totals.locales, 'locales')}
    ${stat(totals.namespaces, 'namespaces')}
    ${stat(totals.keys, 'distinct keys')}
    ${stat(totals.files, 'files scanned')}
    ${stat(totals.findings, 'findings')}
  </div>

  <div class="coverage">
    <div class="coverage-head">
      <h2>Key coverage</h2>
      <p class="blind">
        fog <strong>${round(keys.fogPct)}%</strong> ·
        unattributed <strong>${round(keys.unattributedPct)}%</strong> ·
        <strong>${blind}%</strong> of keys cannot be judged
      </p>
    </div>
    <div class="bar" role="img" aria-label="${escapeHtml(
      buckets.map(([, label, value]) => `${value} ${label}`).join(', '),
    )}">
      ${buckets
        .filter(([, , value]) => value > 0)
        .map(([role, , value]) => `<span class="b-${role}" style="flex:${value}"></span>`)
        .join('\n      ')}
    </div>
    <ul class="bucket-legend">
      ${buckets
        .map(
          ([role, label, value, note]) =>
            `<li><span class="swatch" style="background:var(--${role})"></span>` +
            `<span><b>${value}</b> ${escapeHtml(label)} ` +
            `<span class="note">— ${escapeHtml(note)}</span></span></li>`,
        )
        .join('\n      ')}
    </ul>
  </div>
</header>`
}

function stat(value: number, label: string): string {
  return `<div class="stat"><div class="value">${value}</div><div class="label">${escapeHtml(
    label,
  )}</div></div>`
}

function renderTreemap(report: Report, namespaces: NamespaceView[]): string {
  return `<section class="card">
  <div class="section-head">
    <h2>Namespaces</h2>
    <p>Sized by declared keys, coloured by share of keys that are dead or duplicated.</p>
  </div>
  <ul class="legend">
    <li><span class="swatch good"></span>clean</li>
    <li><span class="swatch warning"></span>minor — under 25%</li>
    <li><span class="swatch serious"></span>notable — 25–50%</li>
    <li><span class="swatch critical"></span>severe — over 50%</li>
  </ul>
  <div id="treemap"></div>
  <details class="table-view">
    <summary>Table view</summary>
    <table>
      <thead>
        <tr>
          <th scope="col">Namespace</th>
          <th scope="col" class="num">Keys</th>
          <th scope="col" class="num">Dead</th>
          <th scope="col" class="num">Duplicated</th>
          <th scope="col">Health</th>
        </tr>
      </thead>
      <tbody>
        ${namespaces
          .map(
            (ns) =>
              `<tr><td>${escapeHtml(ns.name)}</td><td class="num">${ns.keys}</td>` +
              `<td class="num">${ns.dead.length}</td><td class="num">${ns.duplicated}</td>` +
              `<td>${SEVERITY_LABEL[ns.severity]}</td></tr>`,
          )
          .join('\n        ')}
      </tbody>
    </table>
  </details>
  <p class="empty">${report.summary.namespaces.length === 0 ? 'No namespaces found.' : ''}</p>
</section>`
}

function renderNamespaceDetail(ns: NamespaceView, initial: string | undefined): string {
  return `<section class="card ns-detail t-${ns.severity}${
    ns.name === initial ? ' is-selected' : ''
  }" data-ns="${escapeHtml(ns.name)}">
  <div class="detail-head">
    <h2>${escapeHtml(ns.name)}</h2>
    <span class="pill">${ns.keys} keys · ${SEVERITY_LABEL[ns.severity]}</span>
  </div>

  <div class="finding-group">
    <h3>Dead keys <span class="count">${ns.dead.length}</span></h3>
    ${
      ns.dead.length === 0
        ? '<p class="empty">None — every declared key is referenced, fogged or widened.</p>'
        : `<ul class="rows">
      ${ns.dead
        .map(
          (finding) =>
            `<li><div class="k">${keyMarkup(finding.key)}</div>` +
            `<div class="meta">declared in ${escapeHtml(finding.locales.join(', '))}</div></li>`,
        )
        .join('\n      ')}
    </ul>`
    }
  </div>

  <div class="finding-group">
    <h3>Value duplicates <span class="count">${ns.duplicates.length}</span></h3>
    ${
      ns.duplicates.length === 0
        ? '<p class="empty">None — no text here is repeated in another namespace.</p>'
        : ns.duplicates
            .map(
              (finding) => `<div class="cluster">
      <div class="value"><span class="q">&ldquo;</span>${escapeHtml(
        finding.value,
      )}<span class="q">&rdquo;</span></div>
      <div class="meta">locale ${escapeHtml(finding.locale)} · ${
        finding.keys.length
      } keys share this text</div>
      <ul>
        ${finding.keys.map((key) => `<li class="k">${keyMarkup(key)}</li>`).join('\n        ')}
      </ul>
    </div>`,
            )
            .join('\n    ')
    }
  </div>
</section>`
}

function renderGlobalFindings(conventions: Convention[], localeGaps: LocaleGap[]): string {
  return `<section class="card">
  <div class="section-head">
    <h2>Across namespaces</h2>
    <p>Findings that belong to a file or a locale rather than to one namespace.</p>
  </div>

  <div class="finding-group">
    <h3>Convention <span class="count">${conventions.length}</span></h3>
    ${
      conventions.length === 0
        ? '<p class="empty">None — no file binds more namespaces than allowed.</p>'
        : `<ul class="rows">
      ${conventions
        .map(
          (finding) =>
            `<li><div class="k">${escapeHtml(finding.file)}</div>` +
            `<div class="meta">binds ${finding.namespaces.length} namespaces: ` +
            `${escapeHtml(finding.namespaces.join(', '))}</div></li>`,
        )
        .join('\n      ')}
    </ul>`
    }
  </div>

  <div class="finding-group">
    <h3>Locale gaps <span class="count">${localeGaps.length}</span></h3>
    ${
      localeGaps.length === 0
        ? '<p class="empty">None — every key is declared in every locale.</p>'
        : `<ul class="rows">
      ${localeGaps
        .map(
          (finding) =>
            `<li><div class="k">${keyMarkup(finding.key)}</div>` +
            `<div class="meta">in ${escapeHtml(finding.presentIn.join(', '))} · ` +
            `missing from ${escapeHtml(finding.missingIn.join(', '))}</div></li>`,
        )
        .join('\n      ')}
    </ul>`
    }
  </div>
</section>`
}

/** Render a KeyId with its namespace prefix de-emphasised. */
function keyMarkup(keyId: string): string {
  const at = keyId.indexOf(':')
  if (at === -1) return escapeHtml(keyId)
  return `<span class="ns">${escapeHtml(keyId.slice(0, at + 1))}</span>${escapeHtml(
    keyId.slice(at + 1),
  )}`
}

/** Trim float noise from summing two already-rounded percentages. */
function round(value: number): number {
  return Math.round(value * 10) / 10
}
